### PR TITLE
FATS selection must be 1.5MB above

### PR DESCRIPTION
**Pull request by xiaolaba**
hi, this is user feedback for the clone and and how to build if NTP failed.

### CODE REVIEW

**Comment by BojanJurca** [comment]
Thank you for testing Xiaolaba, very much. Are you sure that NTP failure was caused by smaller flash disk space? 

It doesn't make sense to me since NTP does not use a file system at all. Besides 1.5 MB FATFS works fine for me.

**Comment by BojanJurca** [comment]
Would you please telnet to your ESP32 and type dmesg command? You should be able to get some messages that would tell you if something went wrong. The beginning of dmesg response should look something like this:

# dmesg 
[ 0] [ESP32] CPU0 reset reason: RTCWDT_RTC_RESET - 16, RTC Watch dog reset digital core and rtc module 
[ 0] [ESP32] CPU1 reset reason: EXT_CPU_RESET - 14, for APP CPU, reseted by PRO CPU 
[ 1] [ESP32] wakeup reason: WAKEUP REASON UNKNOWN - wakeup was not caused by deep sleep: 0. 
[ 2] [ESP32] ESP32 NodeMCU (160 MHz) ESP_4 SDK v3.2.3-14-gd3e562907 SRV32-1.26 dev (re)started 1. time and has not obtained current time yet. 
[ 0] [file system] mounted. 
[ 0] [cronDaemon] started. 
[ 0] [network] starting WiFi 
[ 0] [network] [STA] connecting STAtion to router using DHCP. 
[ 0] [network] [STA] WiFi client started. 
[ 0] [httpServer] started on 0.0.0.0:80. 
[ 0] [ftpServer] started on 0.0.0.0:21. 
[ 0] [telnetServer] started on 0.0.0.0:23. 
[ 0] [network] [STA] connected to WiFi ***********. 
[ 0] [network] [STA] got IP address: 10.0.0.4. 
[ 0] [time] synchronized with 1.si.pool.ntp.org 
[1613850860] [time] time set to 2021/02/20 20:54:20.

**Comment by xiaolaba** [comment]
hi, the telnet was not capable anyway, looks like something odd, the connection forced abort immediately.

telnet setup like this,
telnet_setup

no connection done,
telnet_NG


> 
> 
> Would you please telnet to your ESP32 and type dmesg command? You should be able to get some messages that would tell you if something went wrong. The beginning of dmesg response should look something like this:
> # dmesg
> 
> [ 0] [ESP32] CPU0 reset reason: RTCWDT_RTC_RESET - 16, RTC Watch dog reset digital core and rtc module
> [ 0] [ESP32] CPU1 reset reason: EXT_CPU_RESET - 14, for APP CPU, reseted by PRO CPU
> [ 1] [ESP32] wakeup reason: WAKEUP REASON UNKNOWN - wakeup was not caused by deep sleep: 0.
> [ 2] [ESP32] ESP32 NodeMCU (160 MHz) ESP_4 SDK v3.2.3-14-gd3e562907 SRV32-1.26 dev (re)started 1. time and has not obtained current time yet.
> [ 0] [file system] mounted.
> [ 0] [cronDaemon] started.
> [ 0] [network] starting WiFi
> [ 0] [network] [STA] connecting STAtion to router using DHCP.
> [ 0] [network] [STA] WiFi client started.
> [ 0] [httpServer] started on 0.0.0.0:80.
> [ 0] [ftpServer] started on 0.0.0.0:21.
> [ 0] [telnetServer] started on 0.0.0.0:23.
> [ 0] [network] [STA] connected to WiFi ***********.
> [ 0] [network] [STA] got IP address: 10.0.0.4.
> [ 0] [time] synchronized with 1.si.pool.ntp.org
> [1613850860] [time] time set to 2021/02/20 20:54:20.

hi, the telnet was not capable anyway, looks like something odd, the connection forced abort immediately.

telnet setup like this,
telnet_setup

no connection done,
telnet_NG

**Comment by xiaolaba** [comment]
> 
> 
> Would you please telnet to your ESP32 and type dmesg command? You should be able to get some messages that would tell you if something went wrong. The beginning of dmesg response should look something like this:
> # dmesg
> 
> [ 0] [ESP32] CPU0 reset reason: RTCWDT_RTC_RESET - 16, RTC Watch dog reset digital core and rtc module
> [ 0] [ESP32] CPU1 reset reason: EXT_CPU_RESET - 14, for APP CPU, reseted by PRO CPU
> [ 1] [ESP32] wakeup reason: WAKEUP REASON UNKNOWN - wakeup was not caused by deep sleep: 0.
> [ 2] [ESP32] ESP32 NodeMCU (160 MHz) ESP_4 SDK v3.2.3-14-gd3e562907 SRV32-1.26 dev (re)started 1. time and has not obtained current time yet.
> [ 0] [file system] mounted.
> [ 0] [cronDaemon] started.
> [ 0] [network] starting WiFi
> [ 0] [network] [STA] connecting STAtion to router using DHCP.
> [ 0] [network] [STA] WiFi client started.
> [ 0] [httpServer] started on 0.0.0.0:80.
> [ 0] [ftpServer] started on 0.0.0.0:21.
> [ 0] [telnetServer] started on 0.0.0.0:23.
> [ 0] [network] [STA] connected to WiFi ***********.
> [ 0] [network] [STA] got IP address: 10.0.0.4.
> [ 0] [time] synchronized with 1.si.pool.ntp.org
> [1613850860] [time] time set to 2021/02/20 20:54:20.

hi, the telnet was not capable anyway, looks like something odd, the connection forced abort immediately.

telnet setup like this,
telnet_setup

no connection done,
telnet_NG

**Comment by BojanJurca** [comment]
I see you are using putty that connects to ESP32 through AP.  I can also see that websocket communication is not working for you. I'll do the checking and let you know what I find out.

**Comment by BojanJurca** [comment]
But let's go to initial issue for a while - NTP not working. 

- Does your ESP32 have internet access? If it doesn't then it can not access NTP servers. You have to configure also STA(tion) WiFi mode (besides AP) to connect your ESP32 to WiFi router. 
- You may also want to check if NTP servers 1.si.pool.ntp.org, ... can be accessed from your location and perhaps configure different ones if necessary.

If you don't connect ESP32 to WiFi router you can still set time manually by using date telnet command but we have to make telnet working first. I'll let you know.

**Comment by BojanJurca** [comment]
I believe I have solved putty problem. I have just uploaded a new telnetServer.hpp. Please replace your old one then putty telnet connection should work. You should be able to check dmesg now.

**Comment by xiaolaba** [comment]
> 
> 
> I believe I have solved putty problem. I have just uploaded a new telnetServer.hpp. Please replace your old one then putty telnet connection should work. You should be able to check dmesg now.


thanks, telnet is working.
telnet_fixed


And we are able to manage this issue finally, perhaps Arduino IDE did not erase the chip completely before burn code and rendered something odd.

To uses a new chip and/or erase the chip on the own, it is able to uses 1.5MB FATFS finally, NTP is working too.


here is the batch file used for investigation and workaround,

`
:: To erase esp32 completely, do not rely on Arduino IDE and code upload, it has cluster and odd thing when uses FATFS.
:: xiaolaba, 2020-MAR-02

:: Arduino 1.8.13, esptool and path,
set esptool=C:\Users\user0\AppData\Local\Arduino15\packages\esp32\tools\esptool_py\3.0.0/esptool.exe

:: erase whole flash of esp32
%esptool% --chip esp32 --port com5 --baud 921600 erase_flash

pause

`

**Review by BojanJurca — COMMENTED** [review]
I like the idea of putting links to all examples into index.html. How can I commit your pull request?

**Comment by xiaolaba** [comment]
> 
> 
> I like the idea of putting links to all examples into index.html. How can I commit your pull request?

I am quite new to git or github for the pull/merge things, sometime just did not work out those by myself, so most of the time I used upload direct.
you may like to look at this https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/merging-a-pull-request.

or... there is the code
`     

        <H1>
         <a href="index.html">index.html</a></br> 
         <a href="example02.html">example02.html</a></br> 
         <a href="example03.html">example03.html</a></br> 
         <a href="example04.html">example04.html</a></br> 
         <a href="example05.html">example05.html</a></br> 
         <a href="example10.html">example10.html</a></br> 
         <a href="login.html">example7 login.html</a></br>                       
         <a href="oscilloscope.html">oscilloscope.html</a></br>                           

        </H1>
        
	</body>
</html>
`

**Pull request closed without merging**
