### PR TITLE
pull

### PR DESCRIPTION
**Pull request by xiaolaba**

### CODE REVIEW

**Comment by BojanJurca** [comment]
index.html

**Comment by BojanJurca** [comment]
Hello xiaolaba,

I've noticed that your pull request didn't quite merge correctly, quite some time ago. There has been a lot of changes since so I can not merge it again. Please, make another pul request just for index.html so we can put things in order.

Thank you.

**Comment by xiaolaba** [comment]
> Hello xiaolaba,
> 
> I've noticed that your pull request didn't quite merge correctly, quite some time ago. There has been a lot of changes since so I can not merge it again. Please, make another pul request just for index.html so we can put things in order.
> 
> Thank you.

hi, did you mean this index,html ?
https://github.com/xiaolaba/Esp32_web_ftp_telnet_server_template_tesing_2021-MAR-02/blob/master/html/index.html

**Comment by BojanJurca** [comment]
Perhaps rather the latest one. If I reponen your pull request, many older files will get merged ...

**Review by BojanJurca — APPROVED** [review]

**Pull request closed without merging**
